name: Run BookingIntegrationTest and Email on Success

on:
  push:
    branches: [ "main" ]

jobs:
  run-booking-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run BookingIntegrationTest.java
        run: mvn compile exec:java

      - name: Send Email on Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: mail.protonmail.ch
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: GitHub Actions Build Success 🚀
          to: ${{ secrets.EMAIL_RECEIVER }}
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
          body: |
            ✅ CI Pipeline Success for BookingIntegrationTest.java
            
            Triggered by: Push to main branch
            Status: SUCCESS
            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Job: ${{ github.job }}
            Run ID: ${{ github.run_id }}
